#!/bin/sh

gtk-query-immodules-3.0 --update-cache
#im-switch -s lmp

# If no root access, lmp-im modules and data can be installed like this:
#   ~/.gtk-2.0/immodules/       - lmp-im.so or other immodules
#   ~/.gtk-2.0/gtk-immodules    - point GTK_IM_MODULE_FILE to this file
#   ~/.lmp-im/                   - lmp-im tables

# Note for GNOME

# Since GTK+ 2.8, showing input methods in popup menu is controlled
# by "gtk-show-input-method-menu" setting.  It may be FALSE by
# default.  Change it using gconf-editor through
#   desktop->gnome->interface->show_input_method_menu
